version: '3'
services:
  nodejs:
      build:
        context: .
        dockerfile: ./Appeatite_Server/Dockerfile.dev
      restart: always
      ports:
        - 3000:3001
        - 3001:3002
      links:
        - mongo
      volumes:
        - ./Appeatite_Server:/usr/src/app
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASS: postgres
        POSTGRES_DB: appeatite
        PORT: 3001
        SOCKET_PORT: 3002
        SETU_SANDBOX_URL: "https://uat.setu.co/api"
        SETU_PROD_URL: "https://prod.setu.co/api"
        DEVELOPMENT: 1
      depends_on:
        - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appeatite
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jay@appeatite.in
      PGADMIN_DEFAULT_PASSWORD: jayvishaal
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
 mongodb:
 db-data:
 pgadmin-data:
